# Generated by Django 4.0.4 on 2022-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Brand nomi')),
                ('slug', models.SlugField(verbose_name='Slugi *')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(verbose_name='Slugi *')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rangi')),
                ('english_name', models.CharField(max_length=100, verbose_name='Rangning nomi (inglizcha)')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('surname', models.CharField(max_length=255, verbose_name='Familya')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email pochta')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rasm nomi (agar rasm topilmasa)')),
                ('image', models.ImageField(upload_to='products/%y-%m-%d', verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tovar nomi')),
                ('slug', models.SlugField(verbose_name='Tovar slugi *')),
                ('description', models.TextField(verbose_name='Tovar haqida')),
                ('cost', models.PositiveIntegerField(verbose_name='Tovar narxi "$" (100)')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirmasi bormi ?')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agar chegirmasi bor bolsa necha foiz')),
                ('most_purchased', models.BooleanField(default=False, verbose_name='Tovar kop sotiladiganmi ?')),
                ('poster', models.ImageField(upload_to='poster/%y/%m/%d/', verbose_name='Tovar posteri')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Sotilib bolindimi ?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.brand', verbose_name='Tovar brandi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.category', verbose_name='Tovar kategoriyasi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.color', verbose_name='Tovar rangi')),
                ('product_images', models.ManyToManyField(to='common.productimages', verbose_name='Tovar rasmlari')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner nomi')),
                ('description', models.TextField(verbose_name='Banner haqida')),
                ('image', models.ImageField(upload_to='banner/%y-%m-%d', verbose_name='Banner rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category', verbose_name='Banner kategoriyasi')),
            ],
        ),
    ]
