# Generated by Django 4.0.4 on 2022-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Jami soni')),
                ('total_cost', models.PositiveIntegerField(default=0, verbose_name='Jami narxi')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Toliq ism')),
                ('province', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ("Farg'ona", "Farg'ona"), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=255, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=255, verbose_name='Shahar')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('zipcode', models.CharField(max_length=20, verbose_name="Zip ko'd")),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Yetkazib berildi', 'Yetkazib berildi'), ('Korib chiqilyapti', 'Korib chiqilyapti'), ('Korilmadi', 'Korilmadi')], default='Korilmadi', max_length=255, verbose_name='Holat')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Savatcha')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Mahsulot miqdori')),
                ('cost', models.PositiveIntegerField(verbose_name='Mahsulot narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.product', verbose_name='Mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to='cart.cartproduct', verbose_name='Mahsulotlar'),
        ),
    ]
