# Generated by Django 4.0.4 on 2022-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Zip ko'd"),
        ),
    ]
